version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
